/* Pour Dawgz product catalog.
   Single source of truth for the store. Edit this file to add/remove products.
   - price: number in USD, or null if not yet carried over from the old site.
   - image: local file under images/ (downloaded from the old site).
   - squareLink: Square payment link for this product. "#" = not yet connected.
   - orderLink: link for the "Message Us to Order" button (used while Square checkout is not connected).
   - type: "fixed" (buy now) or "auction" (bid / ask).
   - available: false disables the buy button (e.g. crib listing). */
const PRODUCTS = [
  {
    id: "duluth-pants",
    name: "Duluth Fire Hose Cargo Work Pants, Desert Khaki 32x32",
    price: 119.99,
    description: "Duluth Fire Hose cargo work pants in Desert Khaki, 32x32. Pour Dawgz Owner Picks.",
    image: "images/duluth-pants.jpg",
    squareLink: "#",
    seller: "Pour Dawgz Owner Picks",
    type: "fixed",
    available: true
  },
  {
    id: "powercap-beanie",
    name: "POWERCAP 2.5 Rechargeable LED Beanie, Black Knit",
    price: 34.99,
    description: "POWERCAP 2.5 rechargeable LED beanie in black knit. Pour Dawgz Owner Picks.",
    image: "images/powercap-beanie.jpg",
    squareLink: "#",
    seller: "Pour Dawgz Owner Picks",
    type: "fixed",
    available: true
  },
  {
    id: "volt-gloves",
    name: "Volt Heated 7V Leather Work Gloves, Medium",
    price: 229.99,
    description: "Volt heated 7V leather work gloves, size Medium. Pour Dawgz Owner Picks.",
    image: "images/volt-gloves.png",
    squareLink: "#",
    seller: "Pour Dawgz Owner Picks",
    type: "fixed",
    available: true
  },
  {
    id: "stan-ray-jacket",
    name: "Stan Ray Shop Jacket, Natural Drill (XL)",
    price: 139.95,
    description: "Stan Ray shop jacket in Natural Drill, size XL. Pour Dawgz Owner Picks.",
    image: "images/stan-ray-jacket.jpg",
    squareLink: "#",
    seller: "Pour Dawgz Owner Picks",
    type: "fixed",
    available: true
  },
  {
    id: "neon-tee",
    name: "Pour Dawgz Neon Workshop Tee",
    price: 59.99,
    description: "Pour Dawgz Neon Workshop Tee. Choose color and size (S, M, L, XL, 2XL, 3XL).",
    image: "images/neon-tee.png",
    squareLink: "#",
    seller: "Pour Dawgz",
    type: "fixed",
    available: true,
    options: "Sizes S–3XL"
  },
  {
    id: "skill-tee",
    name: "Pour Dawgz Skill & Tools Tee",
    price: 62.99,
    description: "Pour Dawgz Skill & Tools Tee. Choose color and size (S, M, L, XL, 2XL, 3XL).",
    image: "images/skill-tee.png",
    squareLink: "#",
    seller: "Pour Dawgz",
    type: "fixed",
    available: true,
    options: "Sizes S–3XL"
  },
  {
    id: "cuff-beanie",
    name: "Pour Dawgz Logo Cuff Beanie",
    price: 49.95,
    description: "Pour Dawgz logo cuff beanie. Extra photos: images/cuff-beanie-2.png, images/cuff-beanie-3.png.",
    image: "images/cuff-beanie-1.png",
    squareLink: "#",
    seller: "Pour Dawgz",
    type: "fixed",
    available: true
  },
  {
    id: "no-job-tee",
    name: "Pour Dawgz No Job Too Big Tee",
    price: 61.99,
    description: "Pour Dawgz No Job Too Big Tee. Choose color and size (S, M, L, XL, 2XL, 3XL).",
    image: "images/no-job-tee.png",
    squareLink: "#",
    seller: "Pour Dawgz",
    type: "fixed",
    available: true,
    options: "Sizes S–3XL"
  },
  {
    id: "crib",
    name: "Crib",
    price: null,
    description: "Older crib for kid, no mattress, but it's cool. Listed by Riders. Pickup or shipping.",
    image: "images/crib.jpeg",
    squareLink: "#",
    seller: "Riders",
    type: "fixed",
    available: false
  },
  {
    id: "trailer-plate",
    name: "vintage 1975 South Dakota trailer plate",
    price: 5,
    priceLabel: "Starting bid: $5.00",
    description: "Vintage 1975 South Dakota trailer plate. Auction — 0 bids, next bid $5, ends Sep 26, 2026, 6:02 PM. Listed by witchy witch drop in. Pickup or shipping.",
    image: "images/trailer-plate.jpg",
    squareLink: "#",
    seller: "witchy witch drop in",
    type: "auction",
    available: true
  },
  {
    id: "yofidra-angle-grinder",
    name: "YOFIDRA Brushless 125mm (5-inch) Cordless Angle Grinder",
    price: 34.09,
    description: "Brushless cordless angle grinder with 125mm (5-inch) disc, 20,000 RPM max speed, and 14mm disc bore. 4.9-star rating with 1,000+ sold. Tool only - battery NOT included. Free US shipping, delivery Sep 26 - Oct 1.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Se3f478c0ed214ac29c437470f2142ed1v.jpg",
    squareLink: "https://square.link/u/MMRZFC3R",
    externalLink: "https://www.aliexpress.us/item/3256810467309266.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "electric-goddess-recip-saw",
    name: "Electric Goddess Cordless Reciprocating Saw",
    price: 38.09,
    description: "Sawzall-style cordless reciprocating saw for cutting wood and metal. 4.9-star rating, 99 sold. Tool only - battery NOT included (fits DeWalt 20V batteries). Free US shipping, delivery Sep 26 - Oct 1.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sda0836da87b2475b9d78b067f6b87b5ap.png",
    squareLink: "https://square.link/u/ZViv2lX6",
    externalLink: "https://www.aliexpress.us/item/3256809419115120.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "yofidra-multi-tool",
    name: "YOFIDRA Oscillating Multi-Tool",
    price: 57.13,
    description: "600W oscillating multi-tool: up to 20,000 oscillations/min with a 4-degree oscillation angle for cutting, sanding, and scraping. 4.7-star rating, 700+ sold, 124 reviews. Tool only - battery NOT included (works with 21V/18V batteries). Free US shipping, delivery Sep 26 - Sep 30.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Se6e59eaca5b74767b1e4598db79719c0L.jpg",
    squareLink: "https://square.link/u/fipfjYE4",
    externalLink: "https://www.aliexpress.us/item/3256807462426939.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "tdfr-multi-pocket-overalls",
    name: "TDFR Multi-Pocket Denim Overalls - Men's Cargo Bib",
    price: 36.71,
    description: "Men's multi-pocket denim cargo bib overalls: durable midweight cotton-blend denim, loose roomy fit, functional tool pockets, zipper fly. 4.6-star rating from verified buyers, 36 sold. Sizes XS-XXL in Blue or Black. Free returns within 15 days; delivery Sep 27 - Oct 3.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sc9168362ea394f33abdf980e467fcd5b8.jpg",
    squareLink: "https://square.link/u/khAlR8Kn",
    externalLink: "https://www.aliexpress.us/item/3256802713548400.html",
    seller: "Pour Dawgz Workwear",
    type: "fixed",
    available: true
  },
  {
    id: "pourdawgz-tee-logo-front",
    name: "Pour Dawgz Tee - Logo Front",
    price: 34.99,
    description: "Unisex Staple T-Shirt (Bella + Canvas 3001) in Black with large front logo print. Sizes XS-5XL.",
    image: "images/browser-download-20260921T180306.622521264Z-0-unisex-staple-t-shirt-black-front-6ab1714e8d231.png",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Merch",
    type: "fixed",
    available: true
  },
  {
    id: "pourdawgz-tee-handyman-slogan",
    name: "Pour Dawgz Tee - Handyman Slogan",
    price: 34.99,
    description: "Unisex Staple T-Shirt (Bella + Canvas 3001) in Black. Front print: 'HANDYMAN' with the slogan 'Can't be no geek off the street — gotta be handy with the tools.' Sizes XS-5XL.",
    image: "images/browser-download-20260921T180444.572019898Z-1-unisex-staple-t-shirt-black-front-6ab171b11c75a.png",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Merch",
    type: "fixed",
    available: true
  },
  {
    id: "pourdawgz-hoodie-back-logo",
    name: "Pour Dawgz Hoodie - Back Logo",
    price: 59.99,
    description: "Unisex Heavy Blend Hoodie (Gildan 18500) in Black. Big logo on the back, 'Works hard, plays even harder' on the front chest, 'FAFO' and 'GUILD' on the sleeves. Sizes S-5XL.",
    image: "images/unisex-heavy-blend-hoodie-black-front-6ab171fd1f236.png",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Merch",
    type: "fixed",
    available: true
  },
  {
    id: "mini-cob-work-flashlight",
    name: "Mini Magnetic COB Work Flashlight, 800 Lumens",
    price: 4.99,
    description: "Pocket-size magnetic COB work flashlight: 800 lumens, 7 light modes, USB rechargeable. 4.8-star rating, 50,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S3ee48a971784414e90dc3853d31a28ebP.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "magnetic-led-work-light-bar",
    name: "Magnetic LED Work Light Bar, 3 Modes + Power Bank",
    price: 11.99,
    description: "Magnetic LED work light bar: 3 light modes, IP66 waterproof, doubles as an emergency power bank. 4.9-star rating, 5,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sf5b06b7858fc470495f6a32ce9f64c47Q.png",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "motion-sensor-headlamp",
    name: "Motion-Sensor LED Headlamp, 18650 Rechargeable",
    price: 9.99,
    description: "Motion-sensor LED headlamp with 18650 rechargeable battery and high-power COB lamp for hands-free work. 4.9-star rating, 10,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Se140a1ac82e14707bf881c274216fa13A.png",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "magnetic-wrist-strap",
    name: "Magnetic Wrist Strap for Screws and Nails",
    price: 2.99,
    description: "Adjustable heavy-duty magnetic wrist strap holds screws, nails, and small metal tools while you work. 4.9-star rating, 50,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S132a315bc9cc4d94b510dc34471affdao.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "telescopic-magnetic-pickup-tool",
    name: "Telescopic Magnetic Pickup Tool with Pocket Clip",
    price: 4.99,
    description: "Flexible telescopic magnetic pickup tool with pocket clip for grabbing small parts, keys, and screws in tight spots. 4.8-star rating, 1,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S552c107bf74945ed9cbd4611cd3564f9K.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "folding-multitool-pliers",
    name: "Stainless Steel Folding Multi-Tool Pliers",
    price: 6.99,
    description: "Stainless steel folding multi-tool pliers for camping, survival, and everyday jobs. 4.9-star rating, 10,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S226b0b421d2947a4b2e374be8093621fY.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "glow-in-the-dark-tape",
    name: "Green Glow-in-the-Dark Tape, Self-Adhesive",
    price: 3.99,
    description: "Green glow-in-the-dark self-adhesive luminous tape for stairs, walls, and safety marking. 4.9-star rating, 5,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S33c4721651894f9abf396bcd322c9be6K.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "heavy-duty-tool-backpack",
    name: "Heavy-Duty Tool Backpack with Removable Organizer",
    price: 39.99,
    description: "Heavy-duty tool backpack with padded shoulder straps and removable tool organizer; water-resistant, built for electricians and techs. 4.6-star rating, 1,000+ sold, top selling on AliExpress.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sdaa79aebbf2a4befb01e0ba3119535c7Z.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "rechargeable-tactical-flashlight",
    name: "Rechargeable Tactical Flashlight, Zoomable",
    price: 8.99,
    description: "Super-bright rechargeable tactical flashlight: zoomable beam, digital display, waterproof for camping and work. 4.9-star rating, 5,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sbb2ceee410544de8879b719c67ec0b87l.png",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "keychain-multitool-6in1",
    name: "6-in-1 Keychain Multi-Tool",
    price: 2.99,
    description: "6-in-1 folding keychain multi-tool: opener, screwdriver, and pocket plier for everyday carry. 4.9-star rating, 5,000+ sold. Delivery Sep 27 - Oct 2.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sd8e4c8311cd04ef3b727d824531e6cc0I.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "cordless-2in1-nailer-stapler",
    name: "Cordless 2-in-1 18 Gauge Finish Nailer & Stapler",
    price: 59.99,
    description: "Cordless 2-in-1 electric nail gun: fires 18-gauge brad nails (F15-F32) and staples. Depth adjustment for flush finishes. 4.9-star rating, 563 sold. Tool only - battery NOT included (fits Makita 18V batteries). Free US shipping.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S171be7719b3e45089ab87e2b55dd8245S.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "heated-motorcycle-winter-gloves",
    name: "Heated Motorcycle Winter Gloves",
    price: 34.99,
    description: "Heated winter motorcycle/tactical gloves: warm thermal lining, waterproof shell, cycling design. 4.9-star rating, 2,000+ sold.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S78da89d7f11c472b83f293191c66a563b.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "electric-heated-winter-gloves",
    name: "Electric Heated Winter Gloves, Waterproof Rechargeable",
    price: 29.99,
    description: "Electric heated winter gloves with rechargeable heating: warm, waterproof, made for snowmobile and motorcycle riding. 4.9-star rating, 1,000+ sold.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sb411a6cc3b6342c588d267246aa92b23p.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "5-point-safety-harness-ce",
    name: "5-Point Full-Body Safety Harness, CE Certified",
    price: 49.99,
    description: "5-point full-body safety harness for roofing, construction, and high-altitude work. CE certified with heavy-duty webbing and alloy steel D-rings/buckles. Early buyer review: well made, comfortable, sturdy. 5.0-star rating. Free US shipping.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S2ec4d4a8c145422c8373b3376b681782J.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "ce-hard-hat-goggles-visor",
    name: "CE Construction Hard Hat with Goggles Visor, ABS",
    price: 29.99,
    description: "Modern construction hard hat with built-in goggles visor and tough ABS shell. CE certified, ANSI-rated. 4.9-star rating (67 reviews), 600+ sold. Free US shipping.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S7a78a0bb4cd5404b994f473cd5079972U.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "ce-vented-hard-hat-adjustable",
    name: "CE Vented Construction Hard Hat, Adjustable",
    price: 30.99,
    description: "Vented ABS construction hard hat with adjustable ventilation system for all-day comfort on the job site. CE certified. 4.8-star rating (52 reviews). Free US shipping.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S2810a1525fdc4268be2b0fb43fc715f3G.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "safety-glasses-side-shields",
    name: "Anti-Fog Safety Glasses with Side Shields, Clear",
    price: 4.99,
    description: "Clear anti-fog safety glasses with side shields: anti-scratch, anti-blue-light lenses for shop and job-site work. 4.9-star rating (498 reviews).",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Se9d369a1c10140669c8caf9959e9139dg.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "safety-glasses-2pack-ansi-z87",
    name: "2-Pack Clear Safety Glasses, ANSI Z87",
    price: 8.99,
    description: "2-pack of clear safety glasses, ANSI Z87 certified, with anti-fog wrap-around lenses. 5,000+ sold.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/S8787d8b6701447d484bd4454458857dcS.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  },
  {
    id: "sport-safety-goggles-antifog",
    name: "Anti-Fog Sport Safety Goggles, Clear Wrap",
    price: 1.99,
    description: "Budget wrap-around anti-fog safety goggles: anti-splash, dust-proof, adjustable for a secure fit. 4.9-star rating (1,330 reviews), 10,000+ sold.",
    image: "https://ae-pic-a1.aliexpress-media.com/kf/Sbb4d3f79d188429f9672f245816b738eX.jpg",
    squareLink: "#",
    orderLink: "contact.html",
    seller: "Pour Dawgz Tools",
    type: "fixed",
    available: true
  }
];
